package com.qswitch.util;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DukptUtilTest {
    @Test
    void shouldDeriveStableWorkingKeyFromRealDukptFlow() {
        String result = DukptUtil.deriveWorkingKey("0123456789ABCDEFFEDCBA9876543210", "FFFF9876543210E00001");
        assertEquals(32, result.length());
        assertTrue(result.matches("(?i)[0-9a-f]{32}"));
        // Regression vector generated by the current ANSI X9.24 DUKPT implementation.
        assertEquals("042666b49184cfa368de9628d0397bc9", result);
    }

    @Test
    void shouldProduceDifferentKeysForDifferentTransactionCounters() {
        String key1 = DukptUtil.deriveWorkingKey("0123456789ABCDEFFEDCBA9876543210", "FFFF9876543210E00001");
        String key2 = DukptUtil.deriveWorkingKey("0123456789ABCDEFFEDCBA9876543210", "FFFF9876543210E00002");

        assertNotEquals(key1, key2);
    }

    @Test
    void shouldRejectInvalidBdkOrKsnShapes() {
        assertThrows(IllegalArgumentException.class,
            () -> DukptUtil.deriveWorkingKey("ABCDEF1234567890", "FFFF9876543210E00001"));
        assertThrows(IllegalArgumentException.class,
            () -> DukptUtil.deriveWorkingKey("0123456789ABCDEFFEDCBA9876543210", "BAD"));
    }
}
